### ISSUE TITLE
Retry 404's for curl sources

### ISSUE THREAD

**Issue by supakeen** [osbuild/image-builder-cli#40]
(I know this is the wrong place in the stack and we'll need issues in our other projects but I'm listing it here as a user of `image-builder-cli`).

Regularly when building images we get 404's because a mirror isn't fully up to date. We've been wanting to fix that for a while but now we have even more reason to do so:

```
source/org.osbuild.curl (org.osbuild.curl): WARNING: failed to download https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/c/crun-1.19-1.fc41.x86_64.rpm: The requested URL returned error: 404
Traceback (most recent call last):
  File "/usr/bin/osbuild", line 33, in <module>
    sys.exit(load_entry_point('osbuild==138', 'console_scripts', 'osbuild')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/osbuild/main_cli.py", line 183, in osbuild_cli
    manifest.download(object_store, monitor)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/osbuild/pipeline.py", line 421, in download
    source.download(mgr, store)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/osbuild/sources.py", line 39, in download
    reply = client.call("download", args)
  File "/usr/lib/python3.13/site-packages/osbuild/host.py", line 348, in call
    ret, _ = self.call_with_fds(method, args)
             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/osbuild/host.py", line 384, in call_with_fds
    raise error
osbuild.host.RemoteError: RuntimeError: curl: error downloading https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/g/glibc-common-2.40-14.fc41.x86_64.rpm: error code 22,https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/g/glibc-gconv-extra-2.40-14.fc41.x86_64.rpm: error code 22,https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/g/glibc-all-langpacks-2.40-14.fc41.x86_64.rpm: error code 22,https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/c/crun-1.19-1.fc41.x86_64.rpm: error code 22,https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/g/glibc-minimal-langpack-2.40-14.fc41.x86_64.rpm: error code 22,https://mirror.nl.mirhosting.net/fedora/linux/updates/41/Everything/x86_64/Packages/g/glibc-2.40-14.fc41.x86_64.rpm: error code 22
```

**Comment by mvo5** [comment]
Thanks for filing this issue - we also run into this is the bootc-image-builder CI with e.g. the fedora ISO, I would love to see this fixed. It seems the best option is to resurrect https://github.com/osbuild/osbuild/pull/1304 and move to librepo based sources over curl. Does that sound right?

**Comment by supakeen** [comment]
Now that librepo has landed in #51; this ticket c an be closed as `image-builder` does this correctly by default.
